import type { Metadata } from "next";
import { Geist, Geist_Mono, ADLaM_Display } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/aos";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const adlamn = ADLaM_Display({
  variable: "--font-adlamn",
  subsets: ["latin"],
  weight: "400",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${adlamn.variable} antialiased`}
      >
        {children}
        {/*<ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
           
          </ThemeProvider>*/}
         
           <AOSInit />
      </body>
    </html>
  );
}
